### PR TITLE
adding docs

### LINKED ISSUE #4: Fix terraform lint issue
Fix Terraform syntax.

```bash
terraform fmt -recursive
```

### PR DESCRIPTION
**Pull request by Prateeknandle**
adding documentation for official registry
also closes #4

### CODE REVIEW

**Comment by ShubhamTatvamasi** [comment]
Who is reviewing this PR?

**Review by ShubhamTatvamasi — APPROVED** [review]
These docs are generated by `terraform-plugin-docs` and all are properly formatted.

**Comment by ShubhamTatvamasi** [comment]
@Prateeknandle also fix the lint issue.
https://github.com/accuknox/terraform-provider-accuknox/issues/4

**Comment by Prateeknandle** [comment]
@ShubhamTatvamasi can we merge this?

**Comment by ShubhamTatvamasi** [comment]
> @ShubhamTatvamasi can we merge this?

Sure

**Pull request merged**
